services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: chainlit_frontend
    image: phamdt203/chainlit_frontend:latest
    ports:
      - "8002:8002"
    depends_on:
      - backend
    networks:
      - app_network
    volumes:
      - ./frontend:/frontend
      - /frontend/__pycache__

  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: fastapi_backend
    image: phamdt203/fastapi_backend:latest
    ports:
      - "8001:8001"
    networks:
      - app_network
    volumes:
      - ./backend:/src
      - /src/__pycache__

networks:
  app_network:
    driver: bridge
